
version: '3'

services:
  planeta:
    build: planeta
    mem_limit: 512m
    ports:
      - "8080:8080"
    environment:
      spring.datasource.url: jdbc:mysql://planet_market:3306/planeta_bd?createDatabaseIfNotExist=true&serverTimezone=UTC
      spring.datasource.username: root
      spring.datasource.password: 1234
    restart: always
    depends_on:
      planet_market:
          condition: service_healthy
  planet_market:
    image: mysql:8.0.33 
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: planeta_bd
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 10